name: 'bsky-image-bot Post Next Image'
on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    outputs:
      posted_image: ${{ steps.post.outputs.posted_image }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
      
      - name: Post to Bluesky
        id: post
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          LAST_IMAGE_NAME: ${{ vars.LAST_IMAGE_NAME }}
        run: |
          echo "Previous image name: $LAST_IMAGE_NAME"
          yarn --silent run start
          posted_image=$(cat .last_posted_image)
          echo "posted_image=$posted_image" >> $GITHUB_OUTPUT
          echo "Posted image: $posted_image"

      - name: Commit history files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add any history files that were created/updated
          git add -f .large-scale-history.json || true
          git add -f .bot-history.json || true
          git add -f .small-collection-history.json || true
          
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update bot history files [skip ci]"
            git push
            echo "✅ History files committed successfully"
          else
            echo "ℹ️  No history file changes to commit"
          fi

      - name: Update repository variable
        uses: action-pack/set-variable@v1
        with:
          name: 'LAST_IMAGE_NAME'
          value: ${{ steps.post.outputs.posted_image }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}