name: 'bsky-image-bot Post Next Image'
on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

# Grant GITHUB_TOKEN the minimum permissions needed
permissions:
  contents: write      # Required to push commits
  actions: write       # Required to update repository variables

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    outputs:
      posted_image: ${{ steps.post.outputs.posted_image }}
    steps:
      - uses: actions/checkout@v4
        # Uses GITHUB_TOKEN automatically with granted permissions

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Post to Bluesky
        id: post
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          LAST_IMAGE_NAME: ${{ vars.LAST_IMAGE_NAME }}
        run: |
          echo "Previous image name: $LAST_IMAGE_NAME"
          yarn --silent run start
          posted_image=$(cat .last_posted_image)
          echo "posted_image=$posted_image" >> $GITHUB_OUTPUT
          echo "Posted image: $posted_image"

      - name: Commit history files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add history files if they exist
          git add -f .large-scale-history.json || true
          git add -f .bot-history.json || true
          
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update bot history files [skip ci]"
            git push
            echo "✅ History files committed successfully"
          else
            echo "ℹ️  No history file changes to commit"
          fi

      - name: Update repository variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh variable set LAST_IMAGE_NAME --body "${{ steps.post.outputs.posted_image }}"
          echo "✅ Updated LAST_IMAGE_NAME variable"