name: 'bsky-image-bot Post Next Image'
on:
  workflow_dispatch:
  schedule:
  - cron: "0 16-23 * * *"
  - cron: "0 0-4 * * *"

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    outputs:
      posted_image: ${{ steps.post.outputs.posted_image }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
      
      - name: Post to Bluesky
        id: post
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          LAST_IMAGE_NAME: ${{ vars.LAST_IMAGE_NAME }}
        run: |
          echo "Previous image name: $LAST_IMAGE_NAME"
          yarn --silent run start
          posted_image=$(cat .last_posted_image)
          echo "posted_image=$posted_image" >> $GITHUB_OUTPUT
          echo "Posted image: $posted_image"

      - name: Update repository variable
        uses: action-pack/set-variable@v1
        with:
          name: 'LAST_IMAGE_NAME'
          value: ${{ steps.post.outputs.posted_image }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}